import { Wllama } from '@wllama/wllama';
import wasmUrl from '@wllama/wllama/esm/wasm/wllama.wasm?url';

export interface LocalGGUFStatus { ready: boolean; loading: boolean; generating: boolean; webGpuAvailable: boolean; modelName?: string; modelSize?: number; modelFiles: number; contextLength?: number; }
export interface LocalGGUFLoadOptions { contextLength?: number; useGpu?: boolean; onProgress?: (message: string) => void; }
export interface LocalGGUFGenerateOptions { maxTokens?: number; temperature?: number; onToken?: (token: string) => void; }
export interface LocalGGUFMessage { role: 'system' | 'user' | 'assistant'; content: string; }
export interface LocalGGUFBridge { getStatus(): LocalGGUFStatus; load(files: File[], options?: LocalGGUFLoadOptions): Promise<LocalGGUFStatus>; generate(messages: LocalGGUFMessage[], options?: LocalGGUFGenerateOptions): Promise<string>; unload(): Promise<void>; listStored(): Promise<Omit<StoredGGUFModel, 'files'>[]>; save(files: File[]): Promise<string>; loadStored(id: string, options?: LocalGGUFLoadOptions): Promise<LocalGGUFStatus>; loadFromUrl(url: string, options?: LocalGGUFLoadOptions): Promise<LocalGGUFStatus>; deleteStored(id: string): Promise<void>; }
declare global { interface Window { LocalGGUF: LocalGGUFBridge; } }

const MAX_SINGLE_FILE_BYTES = 2 * 1024 * 1024 * 1024;
const DEFAULT_CONTEXT_LENGTH = 2048;
const DEFAULT_MAX_TOKENS = 512;
const GGUF_DB_NAME = 'goldfiredragon-local-models';
const GGUF_DB_VERSION = 2;
const GGUF_STORE = 'models';

type BrowserPerformanceMemory = Performance & { memory?: { jsHeapSizeLimit: number } };
export interface StoredGGUFModel { id: string; name: string; files: { name: string; type: string; size: number; blob: Blob }[]; totalSize: number; createdAt: string; updatedAt: string; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : '알 수 없는 오류가 발생했습니다.'; }
function formatBytes(bytes: number): string { return bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)}KB` : `${(bytes / 1024 / 1024).toFixed(1)}MB`; }
function isGgufName(name: string): boolean { return /\.gguf$/i.test(name) || /\.gguf\.part\d+$/i.test(name) || /-\d{5}-of-\d{5}\.gguf$/i.test(name); }
async function hasGgufMagic(file: File): Promise<boolean> { const h = new Uint8Array(await file.slice(0, 4).arrayBuffer()); return h.length === 4 && h[0] === 0x47 && h[1] === 0x47 && h[2] === 0x55 && h[3] === 0x46; }
function sortFiles(files: File[]): File[] { return [...files].sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true })); }
function assertMemoryBudget(totalBytes: number, contextLength: number) { const memory = (performance as BrowserPerformanceMemory).memory; if (!memory?.jsHeapSizeLimit) return; const estimatedBytes = totalBytes * 1.35 + Math.max(192 * 1024 * 1024, contextLength * 128 * 1024); if (estimatedBytes > memory.jsHeapSizeLimit * 0.8) throw new Error(`선택한 모델(${formatBytes(totalBytes)})은 현재 브라우저 메모리 한도에서 안전하게 실행하기 어렵습니다.`); }
function validateFiles(files: File[]): File[] { const sorted = sortFiles(files); if (!sorted.length) throw new Error('GGUF 모델 파일을 선택하세요.'); if (sorted.some((f) => !isGgufName(f.name))) throw new Error('GGUF 파일과 분할 GGUF 조각만 선택할 수 있습니다.'); if (sorted.some((f) => f.size === 0)) throw new Error('빈 모델 파일은 불러올 수 없습니다.'); if (sorted.some((f) => f.size > MAX_SINGLE_FILE_BYTES)) throw new Error('개별 GGUF 파일이 2GB를 초과합니다.'); return sorted; }
function openGGUFDB(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const req = indexedDB.open(GGUF_DB_NAME, GGUF_DB_VERSION); req.onerror = () => reject(req.error); req.onsuccess = () => resolve(req.result); req.onupgradeneeded = () => { const db = req.result; if (!db.objectStoreNames.contains(GGUF_STORE)) db.createObjectStore(GGUF_STORE, { keyPath: 'id' }); }; }); }
export async function listStoredGGUFModels(): Promise<Omit<StoredGGUFModel, 'files'>[]> { const db = await openGGUFDB(); return new Promise((resolve, reject) => { const req = db.transaction(GGUF_STORE, 'readonly').objectStore(GGUF_STORE).getAll(); req.onsuccess = () => resolve((req.result || []).map(({ files, ...meta }) => meta)); req.onerror = () => reject(req.error); }); }
export async function saveGGUFModel(files: File[], id = `gguf-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`): Promise<string> { const sorted = validateFiles(files); if (!(await hasGgufMagic(sorted[0]))) throw new Error('유효한 GGUF 헤더가 없습니다. 분할 모델은 첫 번째 조각을 포함해야 합니다.'); const now = new Date().toISOString(); const record: StoredGGUFModel = { id, name: sorted[0].name.replace(/\.part\d+$/i, ''), files: sorted.map((file) => ({ name: file.name, type: file.type || 'application/octet-stream', size: file.size, blob: file.slice(0, file.size, file.type) })), totalSize: sorted.reduce((n, f) => n + f.size, 0), createdAt: now, updatedAt: now }; const db = await openGGUFDB(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(GGUF_STORE, 'readwrite'); tx.objectStore(GGUF_STORE).put(record); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error || new Error('GGUF 영구 저장이 중단되었습니다.')); }); return id; }
export async function loadStoredGGUFModel(id: string): Promise<File[]> { const db = await openGGUFDB(); const record: StoredGGUFModel | undefined = await new Promise((resolve, reject) => { const req = db.transaction(GGUF_STORE, 'readonly').objectStore(GGUF_STORE).get(id); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); if (!record) throw new Error('저장된 GGUF 모델을 찾을 수 없습니다.'); return sortFiles(record.files.map((f) => new File([f.blob], f.name, { type: f.type, lastModified: Date.now() }))); }
export async function deleteStoredGGUFModel(id: string): Promise<void> { const db = await openGGUFDB(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(GGUF_STORE, 'readwrite'); tx.objectStore(GGUF_STORE).delete(id); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }

class BrowserGGUFEngine implements LocalGGUFBridge {
  private runtime: Wllama | null = null;
  private status: LocalGGUFStatus = { ready: false, loading: false, generating: false, webGpuAvailable: typeof navigator !== 'undefined' && 'gpu' in navigator, modelFiles: 0 };
  getStatus() { return { ...this.status }; }
  async load(files: File[], options: LocalGGUFLoadOptions = {}) { if (this.status.loading || this.status.generating) throw new Error('현재 로컬 모델 작업이 진행 중입니다.'); const sorted = validateFiles(files); if (!(await hasGgufMagic(sorted[0]))) throw new Error('선택한 첫 파일이 유효한 GGUF 헤더를 포함하지 않습니다.'); const total = sorted.reduce((n, f) => n + f.size, 0); const contextLength = Math.max(512, Math.min(options.contextLength ?? DEFAULT_CONTEXT_LENGTH, 8192)); assertMemoryBudget(total, contextLength); this.status = { ...this.status, ready: false, loading: true, modelFiles: sorted.length }; options.onProgress?.('로컬 GGUF 런타임을 준비하는 중입니다…'); try { await this.unloadRuntime(); const runtime = new Wllama({ default: wasmUrl }, { suppressNativeLog: true, allowOffline: true }); const webGpuAvailable = runtime.isSupportWebGPU(); await runtime.loadModel(sorted, { n_ctx: contextLength, jinja: true, n_threads: Math.max(1, Math.min(navigator.hardwareConcurrency || 2, 4)), ...(options.useGpu === false ? { n_gpu_layers: 0 } : {}) }); this.runtime = runtime; this.status = { ready: true, loading: false, generating: false, webGpuAvailable, modelName: sorted[0].name, modelSize: total, modelFiles: sorted.length, contextLength }; options.onProgress?.('로컬 모델이 준비되었습니다.'); return this.getStatus(); } catch (e) { await this.unloadRuntime(); this.status = { ready: false, loading: false, generating: false, webGpuAvailable: typeof navigator !== 'undefined' && 'gpu' in navigator, modelFiles: 0 }; throw new Error(`GGUF 모델을 불러오지 못했습니다: ${errorMessage(e)}`); } }
  async loadFromUrl(url: string, options: LocalGGUFLoadOptions = {}) { if (this.status.loading || this.status.generating) throw new Error('현재 로컬 모델 작업이 진행 중입니다.'); if (!/^https?:\/\//i.test(url) && !url.startsWith('/')) throw new Error('지원하지 않는 GGUF 모델 URL입니다.'); const contextLength = Math.max(512, Math.min(options.contextLength ?? DEFAULT_CONTEXT_LENGTH, 8192)); await this.unloadRuntime(); const runtime = new Wllama({ default: wasmUrl }, { suppressNativeLog: true, allowOffline: true }); await runtime.loadModelFromUrl(url, { n_ctx: contextLength, jinja: true, n_threads: Math.max(1, Math.min(navigator.hardwareConcurrency || 4, 8)), ...(options.useGpu === false ? { n_gpu_layers: 0 } : {}) } as any); this.runtime = runtime; this.status = { ready: true, loading: false, generating: false, webGpuAvailable: runtime.isSupportWebGPU(), modelName: decodeURIComponent(url.split('/').pop() || 'GGUF'), modelFiles: 1, contextLength }; return this.getStatus(); }
  async generate(messages: LocalGGUFMessage[], options: LocalGGUFGenerateOptions = {}) { if (!this.runtime || !this.status.ready) throw new Error('먼저 로컬 GGUF 모델을 불러오세요.'); if (this.status.generating) throw new Error('이미 로컬 응답을 생성하고 있습니다.'); if (!messages.length) throw new Error('생성할 메시지가 없습니다.'); this.status = { ...this.status, generating: true }; let response = ''; try { const stream = await this.runtime.createChatCompletion({ messages, stream: true, max_tokens: Math.max(1, Math.min(options.maxTokens ?? DEFAULT_MAX_TOKENS, 2048)), temperature: Math.max(0, Math.min(options.temperature ?? 0.7, 2)) }); for await (const chunk of stream) { const token = chunk.choices[0]?.delta?.content ?? ''; if (token) { response += token; options.onToken?.(token); } } if (!response.trim()) throw new Error('모델이 빈 응답을 반환했습니다.'); return response; } catch (e) { throw new Error(`로컬 모델 생성에 실패했습니다: ${errorMessage(e)}`); } finally { this.status = { ...this.status, generating: false }; } }
  listStored() { return listStoredGGUFModels(); }
  save(files: File[]) { return saveGGUFModel(files); }
  loadStored(id: string, options?: LocalGGUFLoadOptions) { return loadStoredGGUFModel(id).then((files) => this.load(files, options)); }
  deleteStored(id: string) { if (this.status.ready || this.status.loading || this.status.generating) return Promise.reject(new Error('현재 사용 중인 모델을 먼저 해제하세요.')); return deleteStoredGGUFModel(id); }
  async unload() { if (this.status.loading || this.status.generating) throw new Error('진행 중인 로컬 작업이 끝난 후 모델을 해제하세요.'); await this.unloadRuntime(); this.status = { ready: false, loading: false, generating: false, webGpuAvailable: typeof navigator !== 'undefined' && 'gpu' in navigator, modelFiles: 0 }; }
  private async unloadRuntime() { if (!this.runtime) return; try { await this.runtime.exit(); } finally { this.runtime = null; } }
}
window.LocalGGUF = new BrowserGGUFEngine();
